import { DifficultyConfig, DifficultyId, ThemeId, ThemeSymbol } from '../types/game';

export const DIFFICULTIES: Record<DifficultyId, DifficultyConfig> = {
  easy: {
    id: 'easy',
    name: 'Fácil (3×4)',
    rows: 3,
    cols: 4,
    pairs: 6,
    previewTimeMs: 1500,
  },
  medium: {
    id: 'medium',
    name: 'Médio (4×4)',
    rows: 4,
    cols: 4,
    pairs: 8,
    previewTimeMs: 2000,
  },
  hard: {
    id: 'hard',
    name: 'Difícil (4×6)',
    rows: 4,
    cols: 6,
    pairs: 12,
    previewTimeMs: 2500,
  },
  expert: {
    id: 'expert',
    name: 'Expert (5×6)',
    rows: 5,
    cols: 6,
    pairs: 15,
    previewTimeMs: 3000,
  },
};

export const THEMES: Record<ThemeId, { name: string; icon: string; symbols: ThemeSymbol[] }> = {
  space: {
    name: 'Espaço & Galáxia',
    icon: '🚀',
    symbols: [
      { id: 's1', emoji: '🚀', name: 'Foguete', color: 'from-blue-500 to-indigo-600' },
      { id: 's2', emoji: '🪐', name: 'Saturno', color: 'from-amber-400 to-orange-600' },
      { id: 's3', emoji: '👾', name: 'Alien', color: 'from-green-400 to-emerald-600' },
      { id: 's4', emoji: '🌟', name: 'Estrela Bright', color: 'from-yellow-300 to-amber-500' },
      { id: 's5', emoji: '🌌', name: 'Via Láctea', color: 'from-purple-500 to-violet-700' },
      { id: 's6', emoji: '☄️', name: 'Cometa', color: 'from-cyan-400 to-blue-600' },
      { id: 's7', emoji: '🛸', name: 'ÓSNI', color: 'from-teal-400 to-emerald-600' },
      { id: 's8', emoji: '🌙', name: 'Lua Crescente', color: 'from-slate-300 to-zinc-500' },
      { id: 's9', emoji: '🛰️', name: 'Satélite', color: 'from-sky-400 to-indigo-500' },
      { id: 's10', emoji: '👩‍🚀', name: 'Astronauta', color: 'from-rose-400 to-pink-600' },
      { id: 's11', emoji: '💥', name: 'Supernova', color: 'from-orange-400 to-red-600' },
      { id: 's12', emoji: '🔭', name: 'Telescópio', color: 'from-indigo-400 to-blue-700' },
      { id: 's13', emoji: '⚡', name: 'Raio Cósmico', color: 'from-amber-300 to-yellow-500' },
      { id: 's14', emoji: '🔮', name: 'Orbe Mística', color: 'from-fuchsia-500 to-purple-700' },
      { id: 's15', emoji: '✨', name: 'Brilho', color: 'from-cyan-300 to-teal-500' },
    ],
  },
  animals: {
    name: 'Mundo Animal',
    icon: '🦁',
    symbols: [
      { id: 'a1', emoji: '🦁', name: 'Leão', color: 'from-amber-500 to-orange-600' },
      { id: 'a2', emoji: '🦊', name: 'Raposa', color: 'from-orange-400 to-red-500' },
      { id: 'a3', emoji: '🐼', name: 'Panda', color: 'from-slate-700 to-zinc-900' },
      { id: 'a4', emoji: '🐯', name: 'Tigre', color: 'from-amber-400 to-orange-500' },
      { id: 'a5', emoji: '🐨', name: 'Koala', color: 'from-slate-400 to-slate-600' },
      { id: 'a6', emoji: '🐸', name: 'Sapo', color: 'from-lime-400 to-emerald-600' },
      { id: 'a7', emoji: '🦄', name: 'Unicórnio', color: 'from-pink-400 to-purple-500' },
      { id: 'a8', emoji: '🦉', name: 'Coruja', color: 'from-amber-700 to-yellow-900' },
      { id: 'a9', emoji: '🐬', name: 'Golfinho', color: 'from-cyan-400 to-blue-600' },
      { id: 'a10', emoji: '🐙', name: 'Polvo', color: 'from-violet-500 to-fuchsia-600' },
      { id: 'a11', emoji: '🦋', name: 'Borboleta', color: 'from-sky-400 to-indigo-500' },
      { id: 'a12', emoji: '🐝', name: 'Abelha', color: 'from-yellow-400 to-amber-500' },
      { id: 'a13', emoji: '🦩', name: 'Flamingo', color: 'from-rose-400 to-pink-500' },
      { id: 'a14', emoji: '🦔', name: 'Oriço', color: 'from-stone-500 to-amber-800' },
      { id: 'a15', emoji: '🦥', name: 'Preguiça', color: 'from-amber-600 to-amber-800' },
    ],
  },
  fantasy: {
    name: 'Fantasia & Magia',
    icon: '🧙‍♂️',
    symbols: [
      { id: 'f1', emoji: '🧙‍♂️', name: 'Mago', color: 'from-purple-600 to-indigo-800' },
      { id: 'f2', emoji: '🐉', name: 'Dragão', color: 'from-red-600 to-rose-800' },
      { id: 'f3', emoji: '⚔️', name: 'Espadas Cruzadas', color: 'from-cyan-500 to-blue-700' },
      { id: 'f4', emoji: '🛡️', name: 'Escudo', color: 'from-slate-500 to-zinc-700' },
      { id: 'f5', emoji: '👑', name: 'Coroa', color: 'from-yellow-400 to-amber-600' },
      { id: 'f6', emoji: '💎', name: 'Gema Mágica', color: 'from-cyan-400 to-teal-600' },
      { id: 'f7', emoji: '🏰', name: 'Castelo', color: 'from-indigo-600 to-violet-800' },
      { id: 'f8', emoji: '🧪', name: 'Poção Mágica', color: 'from-green-400 to-emerald-600' },
      { id: 'f9', emoji: '📜', name: 'Pergaminho', color: 'from-amber-300 to-yellow-600' },
      { id: 'f10', emoji: '🗝️', name: 'Chave Antiga', color: 'from-amber-400 to-yellow-600' },
      { id: 'f11', emoji: '🔥', name: 'Fênix', color: 'from-orange-500 to-red-600' },
      { id: 'f12', emoji: '🧝‍♀️', name: 'Elfa', color: 'from-emerald-400 to-teal-600' },
      { id: 'f13', emoji: '🔱', name: 'Tridente', color: 'from-blue-400 to-indigo-600' },
      { id: 'f14', emoji: '💍', name: 'Anel do Poder', color: 'from-amber-300 to-yellow-500' },
      { id: 'f15', emoji: '🌀', name: 'Portal', color: 'from-fuchsia-500 to-pink-600' },
    ],
  },
  retro: {
    name: 'Arcade Retro',
    icon: '🕹️',
    symbols: [
      { id: 'r1', emoji: '🕹️', name: 'Joystick', color: 'from-red-500 to-rose-700' },
      { id: 'r2', emoji: '🎮', name: 'Controle', color: 'from-indigo-500 to-purple-700' },
      { id: 'r3', emoji: '👾', name: 'Pixel Monster', color: 'from-green-400 to-emerald-600' },
      { id: 'r4', emoji: '🎰', name: 'Slot Machine', color: 'from-yellow-400 to-amber-600' },
      { id: 'r5', emoji: '🎲', name: 'Dado 3D', color: 'from-pink-500 to-rose-600' },
      { id: 'r6', emoji: '🎯', name: 'Alvo', color: 'from-red-500 to-amber-500' },
      { id: 'r7', emoji: '🏆', name: 'Troféu', color: 'from-yellow-300 to-amber-500' },
      { id: 'r8', emoji: '🥇', name: 'Medalha Ouro', color: 'from-amber-400 to-yellow-500' },
      { id: 'r9', emoji: '🎪', name: 'Tenda Retro', color: 'from-red-400 to-indigo-600' },
      { id: 'r10', emoji: '📻', name: 'Rádio Boombox', color: 'from-cyan-500 to-blue-600' },
      { id: 'r11', emoji: '📺', name: 'TV Retro', color: 'from-slate-600 to-zinc-800' },
      { id: 'r12', emoji: '📼', name: 'Fita Cassete', color: 'from-violet-500 to-purple-700' },
      { id: 'r13', emoji: '💣', name: 'Bomba Classic', color: 'from-stone-700 to-zinc-900' },
      { id: 'r14', emoji: '⚡', name: 'Power Up', color: 'from-yellow-400 to-orange-500' },
      { id: 'r15', emoji: '❤️', name: 'Vida Extra', color: 'from-rose-500 to-red-600' },
    ],
  },
};
